# .github/workflows/ci.yml

name: CI Quality Gate

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'prompts/**'
      - '.github/workflows/ci.yml'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and Poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run linter and code formatter check
        run: |
          poetry run ruff check .
          poetry run ruff format --check .

      - name: Run unit tests
        run: |
          poetry run pytest
        env:
          # Disable telemetry to avoid hangs in CI
          POETRY_TELEMETRY_DISABLED: 1

      - name: Custom prompt linter
        run: poetry run python tools/prompt_lint.py prompts/

  security-checks:
    runs-on: ubuntu-latest
    needs: quality-checks
    permissions:
      contents: read # for actions/checkout
      security-events: write # for github/codeql-action/upload-sarif
      actions: read # for github/codeql-action/init to get workflow details
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          # If you wish to specify custom queries, you can do so here
          # queries: +security-extended, +security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
