apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-data-pvc
  namespace: manufacturing-copilot
  labels:
    app: manufacturing-copilot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Update based on cloud provider: gp2 (AWS), pd-standard (GCP), managed (Azure)
  resources:
    requests:
      storage: 10Gi
