# IMPORTANT: This is a template. Do NOT commit actual secrets to Git!
# Create the secret using kubectl:
# kubectl create secret generic manufacturing-copilot-secret \
#   --from-literal=HUGGINGFACE_TOKEN=hf_your_token_here \
#   --namespace=manufacturing-copilot

apiVersion: v1
kind: Secret
metadata:
  name: manufacturing-copilot-secret
  namespace: manufacturing-copilot
  labels:
    app: manufacturing-copilot
type: Opaque
stringData:
  # Replace with your actual token or use kubectl create secret
  HUGGINGFACE_TOKEN: ""  # REQUIRED: Set your HuggingFace token here
  DATABASE_URL: ""  # Optional: PostgreSQL connection string
