apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "manufacturing-copilot.fullname" . }}
  labels:
    {{- include "manufacturing-copilot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "manufacturing-copilot.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "manufacturing-copilot.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "manufacturing-copilot.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            # Application configuration from ConfigMap
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: APP_TITLE
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: APP_VERSION
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: LOG_LEVEL
            - name: ENABLE_TELEMETRY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: ENABLE_TELEMETRY
            # Model configuration
            - name: VLM_MODEL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: VLM_MODEL_ID
            - name: LLM_MODEL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: LLM_MODEL_ID
            - name: EMBEDDING_MODEL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: EMBEDDING_MODEL_ID
            # API configuration
            - name: MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: MAX_RETRIES
            - name: REQUEST_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: REQUEST_TIMEOUT
            - name: TEMPERATURE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: TEMPERATURE
            - name: MAX_TOKENS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: MAX_TOKENS
            # ChromaDB configuration
            - name: CHROMA_PERSIST_DIR
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: CHROMA_PERSIST_DIR
            # Authentication
            - name: VALID_AUTH_TOKEN_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: VALID_AUTH_TOKEN_PREFIX
            # Secrets from Kubernetes Secret
            - name: HUGGINGFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: HUGGINGFACE_TOKEN
            {{- if .Values.secrets.databaseUrl }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "manufacturing-copilot.fullname" . }}
                  key: DATABASE_URL
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: chroma-data
              mountPath: {{ .Values.config.chromaPersistDir }}
            - name: tmp
              mountPath: /tmp
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: chroma-data
          persistentVolumeClaim:
            claimName: {{ include "manufacturing-copilot.fullname" . }}-chroma
        - name: tmp
          emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
