apiVersion: v1
kind: Secret
metadata:
  name: {{ include "manufacturing-copilot.fullname" . }}
  labels:
    {{- include "manufacturing-copilot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.huggingfaceToken }}
  HUGGINGFACE_TOKEN: {{ .Values.secrets.huggingfaceToken | b64enc | quote }}
  {{- else }}
  HUGGINGFACE_TOKEN: ""  # Must be set via --set or external secrets
  {{- end }}
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "manufacturing-copilot.fullname" . }}-chroma
  labels:
    {{- include "manufacturing-copilot.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
